### PR TITLE
Dockerfile supports vat, client commands

### PR DESCRIPTION
**Pull request by dckc**
toward #12 

Usage:

```
~/projects/PlaygroundVat$ docker build -t quorum-vat .
...
Successfully built b48acad55e34
Successfully tagged quorum-vat:latest

~/projects/PlaygroundVat$ docker run --rm -ti --name vat quorum-vat bash

root@569d0d3de82e:/usr/src/app/examples/quorum# ./start.sh

root@569d0d3de82e:/usr/src/app/examples/quorum# grep ++ out/*
out/one:++ wakeupFromTwo we say howdy
out/one:++ responseFromTwo we respond
out/one:++ forwardedFromThree we forward
out/one:++ EVERYTHING WORKS
out/threeA:++ helloThree we say hi y'all
out/threeB:++ helloThree we say hi y'all
out/threeC:++ helloThree we say hi y'all
out/twoA:++ helloTwo morning y'all
out/twoB:++ helloTwo morning y'all
out/twoC:++ helloTwo morning y'all
```

### CODE REVIEW

**Comment by dckc** [comment]
Based on discussion in #12, the container now exposes the `vat` and `client` executables so that you can, for example, run the quorum example starting from outside the container:

```
~/projects/PlaygroundVat/examples/quorum$ VAT="docker run --net host --rm playground vat" ./start.sh
~/projects/PlaygroundVat/examples/quorum$ grep ++ out/*
out/one:++ wakeupFromTwo we say howdy
out/one:++ responseFromTwo we respond
out/one:++ forwardedFromThree we forward
out/one:++ EVERYTHING WORKS
out/threeA:++ helloThree we say hi y'all
out/threeB:++ helloThree we say hi y'all
out/threeC:++ helloThree we say hi y'all
out/twoA:++ helloTwo morning y'all
out/twoB:++ helloTwo morning y'all
out/twoC:++ helloTwo morning y'all

```

**Comment by dckc** [comment]
I'm not sure where Docker usage should be documented.

**Comment by warner** [comment]
Looks good, I'll land this and then we can figure out some docs.

**Comment by zramsay** [comment]
an h3 under [Usage](https://github.com/Agoric/PlaygroundVat/blob/master/docs/usage.md#usage) and in ~/README would be 👍

**Pull request merged**
